name: CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y $(cat system_dependencies.txt)

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create cookies.json file
      run: echo "${{ secrets.COOKIE_JSON }}" > cookies.json
      
    - name: Deploy to Azure
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AZURE_SUBSCRIPTION_KEY: ${{ secrets.AZURE_SUBSCRIPTION_KEY }}
      run: |
        # Your deployment script here, for example:
        az webapp up --name aivoice-eu-t01-app --resource-group AIAssistant --sku FREE

    # Add your test, lint, or build steps here
    # ...
